MOUSEKEY_ENABLE = yes     # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
VIA_ENABLE      = yes    # Enable VIA
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
POINTING_DEVICE_ENABLE 	    = yes
POINTING_DEVICE_DRIVER      = analog_joystick
# BOOTLOADER                  = qmk-dfu
# JOYSTICK_ENABLE = yes     # Joystick Game controller HID Interface
# JOYSTICK_DRIVER = analog  # Stick mode analog or digital
SRC += analog.c
# DYNAMIC_MACRO_ENABLE = yes
